### PR TITLE
Add author field

### PR DESCRIPTION
**Pull request by kraflab**

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]

**Comment by XaserAcheron** [comment]
It's probably worth being clear in the description whether or not the author name gets drawn in the intermission screen if no `levelpic` is provided (i.e. explicitly say it will or it won't). Some folks might expect that to be a thing, while others won't.

**Comment by fabiangreffrath** [comment]
I'm glad that it doesn't raise any expectations. This should be an implementation detail.

**Review by rfomin — APPROVED** [review]

**Comment by XaserAcheron** [comment]
This spec also doubles as documentation for mappers and modders -- it's better to be explicit about it so they know what they're getting.

**Comment by kraflab** [comment]
While I agree with fabian in theory, the spec currently does dictate default behaviour when the levelpic is not set, so it makes sense to be consistent with that. I've updated the default section to account for the author as well.

**Pull request merged**
